
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raj
 */
public class Matrix_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Matrix_Calculator
     */
    public Matrix_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      public String[] getMatrix(String string){
        string=string.trim();       
        int enterIndex=string.indexOf("\n");          // index of enter 
        String substring=string.substring(0,enterIndex);//EXTRACTS FIRST LINE OF MATRIX
        substring=substring.replaceAll("\\s{2,}", " ");// replaces 2 or more consecutive spaces
        substring=substring.trim();
        
        int column=substring.replaceAll("[^ ]", "").length();// replaces all characters except spaces and counting
        column++;
        
        string=string.replaceAll("\\s{2,}", " ");
        string=string.replaceAll("\n", " ");/// replacing enter into spaces ... so as to count no. of exact spaces
        String dummy=string;// making a dummy string to use it next function
      
        int total=dummy.replaceAll("[^ ]", "").length();// repalcing al characters of whole strings
        total++;
        
        String totalInString=String.valueOf(total);
        String columnInString=String.valueOf(column); 
            
        String[] data={string,columnInString,totalInString}; /// Returning Data  from  this point    
        return data;   
    }
        ////Structuring string int 1d array from string  
       public int[] structureMatrix(String matrix,int total1){
         int i;int[] matrixArray=new int[total1];
         int key=0;     
         // extracting each word as a token with StringTokenizer class
         StringTokenizer t=new StringTokenizer(matrix);
         String word="";
         while(t.hasMoreTokens()){
         word=t.nextToken();
         matrixArray[key]=Integer.parseInt(word);  
         key++;
         }
         return matrixArray;  
       }
      //converts 1-D Array to 2-D Array
       public int[][] Two_D_Array(int[] matrix,int row,int column, int x){         // x shows a condition ...for printinf differrent fields
          int [][] Matrix_2D=new int[row][column];
          
          int i,j,key=0;
          for (i=0;i<row;i++)
            { 
          for (j=0;j<column;j++)
            {Matrix_2D[i][j]=matrix[key];
               if(x==1) {jTextArea1.append("  "+Matrix_2D[i][j]);}                 // ULEASING THE BEAST FROM HERE 
               else
               if(x==2) {jTextArea2.append("  "+Matrix_2D[i][j]); }
               else                        
                        {jTextArea3.append("  "+Matrix_2D[i][j]); } 
             key++;
            }
          
              if(x==1)
              {jTextArea1.append("\n");}
              else
              if(x==2)  
              {jTextArea2.append("\n");}
              else 
              {jTextArea3.append("\n");} 
            }
              return Matrix_2D;
       }
     
       
       public int [] operate(int[] matrix1,int[] matrix2,char c){
       
       int i;int l=matrix1.length; 
       int [] result=new int[l];
       
       for (i=0;i<l;i++){
       
           if (c=='+'){
           result[i] =matrix1[i]+matrix2[i];
           }else 
           if (c=='-'){
           result[i] =matrix1[i]-matrix2[i];
           } 
       }// end of for loop  
       return result;
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Matrix  Calculator ");

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("[  A ]");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("[  B ]");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Result:-");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setText("Solve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 153));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton1.setText("Add");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jRadioButton2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton2.setText("Substract");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton3.setText("multiply");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 13)); // NOI18N
        jLabel5.setText(" Md Imran Hussain Productions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        String s1=jTextArea1.getText();
        String s2=jTextArea2.getText();
        int column1,total1,row1,column2,total2,row2;
        String  []data; 
        String matrix1,matrix2;
        int []matrixA;
        int []matrixB;
       
        data = getMatrix(s1);
        matrix1=data[0];
        column1=Integer.parseInt(data[1]);  
        total1=Integer.parseInt(data[2]);
        
        data = getMatrix(s2);
        matrix2=data[0];
        column2=Integer.parseInt(data[1]);  
        total2=Integer.parseInt(data[2]);
       
if((total1%column1==0)&&(total2%column2==0)){
        row1=total1/column1; row2=total2/column2;
        
        matrixA=structureMatrix(matrix1,total1);
        matrixB=structureMatrix(matrix2,total2);
        
        int [][]Matrix1=new int[row1][column1]; 
        int [][]Matrix2=new int[row2][column2];
         
        
        jTextArea1.setText("");
        jTextArea2.setText("");
        
        Matrix1=Two_D_Array(matrixA, row1, column1, 1);
        Matrix2=Two_D_Array(matrixB, row2, column2, 2);
        
        
        ///WORK HERE EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
        
        if(jRadioButton1.isSelected()){
               jTextArea3.setText("");
               if((row1==row2)&&(column1==column2)){ ///Checking Order of the Matrix
        
                    int [] result=operate(matrixA,matrixB,'+');
                    int [][] print =Two_D_Array(result,row1,column1,3); // it doest matter either row1 or row 2 is used  as both are same
                   
                }
               else { 
                 jTextArea3.setText("");
                 jTextArea3.append("MATRIX CANNOT BE FORMED AS THE ORDERS OF "+"\n"+"BOTH MATRIX DON'T MATCH ");///error part when order doesnt match
                }
               
          
        }else
        if(jRadioButton2.isSelected()){
               jTextArea3.setText("");
               if((row1==row2)&&(column1==column2)){                               //Checking Order of the Matrix
        
                   int [] result=operate(matrixA,matrixB,'-');
                   int [][] print =Two_D_Array(result,row1,column1,3);             // it doest matter either row1 or row 2 is used  as both are same
                   
                }
               else { 
                 jTextArea3.setText("");
                 jTextArea3.append("MATRIX CANNOT BE FORMED AS THE ORDERS OF "+"\n"+"BOTH MATRIX DON'T MATCH ");///error part when order doesnt match
                }
               
               
        }else
        if (jRadioButton3.isSelected()){
               jTextArea3.setText("");
               if(column1==row1){                                                 //Checking Order of the Matrix
                   
                   int mc=0,k,i,j,t,m;
                   for(k=0;k<row1;k++)
                   {
                       for (i=0;i<column2;i++)
                      {
                       m=0; t=0;
                          for (j=0;j<row2;j++)
                         {
                            t= Matrix1[k][j]*Matrix2[j][i]+t;
                         }
                          jTextArea3.append(""+t+"  "); 
                      }
                   jTextArea3.append("\n");
                 }
               }
               
               else { 
                 jTextArea3.setText("");
                 jTextArea3.append("The MATRIX NOT DEFINED FOR MULTIPLICATION  "+"\n"+" AS THE ORDER DOES NOT MATCH "); ///error part when order doesnt match
                }                                                                  
        }else{
        jTextArea3.setText("");
        jTextArea3.append("PLEASE CHOOSEONE OF THE OPERATION !!!!");   
        }    
  }

/////////////////////////////////////--------------------ERROR-PART-DISPLAY---//////////////////////////////////////////


if((total1%column1==0)&&(total2%column2!=0))
{jTextArea3.setText("");
  jTextArea3.append("Matrix B is not defined "+"\n"+"so, Arithmetic operation is not possible ");
        }
else
if((total1%column1!=0)&&(total2%column2==0))
{jTextArea3.setText("");
    jTextArea3.append("Matrix A is not defined "+"\n"+"so, Arithmetic operation is not possible ");
        }
        
 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                
 
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

  jTextArea1.setText("");
  jTextArea2.setText("");
  jTextArea3.setText("");
  jRadioButton1.setSelected(false);
  jRadioButton2.setSelected(false);
  jRadioButton3.setSelected(false);
  


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    ///#####################JRADIO BUTTON ###########################################
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
     
        
                   jRadioButton2.setSelected(false);
                   jRadioButton3.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

                   jRadioButton1.setSelected(false);
  
                  jRadioButton3.setSelected(false);   
                


    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed


                     jRadioButton1.setSelected(false);
                     jRadioButton2.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

     ///#####################JRADIO BUTTON  ends ###########################################
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrix_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrix_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
